package com.example.slfastener.model.grnmain

data class UpdateGRNLineItem(
    val balQty: Int,
    val currency: String,
    val defautLocation: Any,
    val discountAmount: Int,
    val grnId: Int,
    val grnLineItemUnit: List<Any>?,
    val grnQty: Int,
    val isEdit: Boolean,
    val isGRNLineItem: Boolean,
    val isQCRequired: Boolean,
    val itemCategory: String,
    val itemCode: String,
    val itemDescription: String,
    val itemGroup: String,
    val itemName: String,
    val lineAmount: String,
    val lineItemId: Int,
    val locationId: Int,
    val locationName: String,
    val mhType: String,
    val poId: Int,
    val poLineItemId: Int,
    val poLineNo: Int,
    val poNumber: String,
    val poQty: Int,
    val poUoM: String,
    val posapLineItemNumber: String,
    val taxId: Int,
    val totalUnit: Int,
    val unitPrice: Int,
)
