package com.example.slfastener.model.grndraftdata

data class GrnLineItem(
    val balQTY: Double,
    val createdBy: String,
    val createdDate: String,
    val defautLocation: Any,
    val gdpoNumber: Any,
    val grnId: Int,
    val grnLineItemUnit: List<GrnLineItemUnit>,
    val grnQty: Double,
    val isActive: Boolean,
    val isQCRequired: Boolean,
    val itemCode: String,
    val itemDescription: String,
    val itemName: String,
    val lineItemId: Int,
    val locationId: Int,
    val mhType: String,
    val modifiedBy: String,
    val modifiedDate: Any,
    val poId: Int,
    val poLineItemId: Int,
    val poLineNo: Int,
    val poNumber: String,
    val poQty: Double,
    val poqty: Double,
    val posapLineItemNumber: String,
    val pouom: String,
    val unitPrice: Any
)