package com.example.slfastener.model.grndraftdata

data class GrnLineItem(
    val lineItemId: Int,
    val grnId: Int,
    val poId: Int,
    val poNumber: String,
    val poLineNo: Int,
    val poLineItemId: Int,
    val itemCode: String,
    val itemName: String,
    val itemDescription: String,
    val itemGroup: String?,
    val itemCategory: String?,
    val mhType: String,
    val poUoM: String,
    val poQty: Double,
    val unitPrice: Int,
    val grnQty: Double,
    val locationId: Int,
    val locationName: String,
    val defautLocation: String?,
    val isQCRequired: Boolean,
    val isExpirable: Boolean,
    val posapLineItemNumber: String,
    val balQty: Double,
    val totalUnit: Int,
    val taxId: Int,
    val taxName: String?,
    val taxCode: String?,
    val taxPercent: Double,
    val discountAmount: Double,
    val poTransaction: String?,

    val grnLineItemUnit: List<GrnLineItemUnit>,
    val isActive: Boolean,
    val createdBy: String,
    val createdDate: String,
    val modifiedBy: String?,
    val modifiedDate: String?
)