package com.example.slfastener.model.polineitemnew


data class GRNUnitLineItemsSaveRequest(
    /*    val GRNId: Int,
        val IsDGPOMandatory: Boolean,
        val IsGRNLineItem: Boolean,
        val balQTY: Double,
        val currency: String,
        val grnLineItemUnit: List<GrnLineItemUnit>,
        val isDelete: Boolean,
        val itemCode: String,
        val itemDescription: String,
        val itemName: String,
        val lineItemId: Int,
        val mhType: String,
        val poId: Int,
        val poLineItemId: Int,
        val poLineNo: Int,
        val poNumber: String,
        val poqty: Double,
        val posapLineItemNumber: String,
        val pouom: String,
        val quantityReceived: String,
        val unitPrice: String*/

    val balQTY: Double,
    val currency: String,
    val defautLocation: Any?,
    val gdpoNumber: Any?,
    val grnId: Int,
    val grnLineItemUnit: List<GrnLineItemUnit>,
    val grnQty: Double,
    val isActive: Boolean,
    val isDelete: Boolean,
    val isQCRequired: Boolean,
    val itemCategory: String,
    val itemCode: String,
    val itemDescription: String,
    val itemGroup: String,
    val itemName: String,
    val lineItemId: Int,
    val locationId: Int,
    val mhType: String,
    val poId: Int,
    val poLineItemId: Int,
    val poLineNo: Int,
    val poNumber: String,
    val poQty: Double,
    val posapLineItemNumber: String,
    val pouom: String,
    val unitPrice: Any?
)